import "./globals.css";
import { NextAuthProvider } from "./context/Provider";
import { Toaster } from "react-hot-toast";
import { Roboto } from 'next/font/google'

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})
export const metadata = {
  title: "Attendance management system",
  description: "Generated by create next app",
};
export default async function RootLayout({ children }) {
  return (
    <html lang="en" className={roboto.className}>
      <body>
        <div>
          <NextAuthProvider>
            <Toaster position="top-right" />
            {children}
          </NextAuthProvider>
        </div>
      </body>
    </html>
  );
}
